### ISSUE TITLE
Application Fixes?

### ISSUE THREAD

**Issue by Luffy2733** [Incredibleflamer/Anime-batch-downloader-gui#14] opened 2024-12-16 13:06 UTC
Hello,

Thank you so much for creating this project! it has helped me download anime much easier and I can't thank you enough :)

I ran into some issues with the application and was wondering if you have advice on these issues.

1) Some anime stop downloading and get stuck all of sudden. Is this a server problem or is there a fix?

![Screenshot 2024-12-15 141952](https://github.com/user-attachments/assets/ae3067f3-5289-4dc4-b24b-f1aa3565aa8f)

2) I get this error sometimes and I'm not sure how to fix it?

![image](https://github.com/user-attachments/assets/40832d66-11af-41f6-a7ca-16c02cb86dad)

3) When Pagination is off it shows duplicates of anime. so should I only download with Pagination on?

![Screenshot 2024-12-16 114445](https://github.com/user-attachments/assets/6a94cf36-4865-4a94-9b71-c34fb6c21fd2)

Thank you :)

**Comment by Incredibleflamer** [comment] 2024-12-17 10:33
Hey! Sorry for the delay. The issue is with extraction in Zoro. Megatube has changed the way it stores videos, so I’ll need some time to sort it out. Additionally, Gogo hasn’t been updated with new episodes yet, so it’s not useful at the moment, making the application currently unusable.

**Comment by Incredibleflamer** [comment] 2024-12-21 10:17
The issue has been fixed in the latest release!
If it still doesn’t work for you, feel free to let me know! 😊

**Closed** 2024-12-21 21:40 UTC
Labels: bug
